services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=47kTcGDRIgb7HXF'
      - 'MYSQL_USER=todo'
      - 'MYSQL_PASSWORD=todo'
      - 'MYSQL_DATABASE=todo_api'
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './data:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
volumes:
  mysql_data:
